### ISSUE TITLE
Ansible Dev branch issues

### ISSUE THREAD

**Issue by johnsondnz** [larsks/ansible-assertive#1]
`Traceback (most recent call last):
  File "/usr/local/bin/ansible-playbook", line 106, in <module>
    exit_code = cli.run()
  File "/usr/local/lib/python2.7/dist-packages/ansible/cli/playbook.py", line 130, in run
    results = pbex.run()
  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/playbook_executor.py", line 89, in run
    self._tqm.load_callbacks()
  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_queue_manager.py", line 178, in load_callbacks
    self._stdout_callback = callback_loader.get(self._stdout_callback)
  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/__init__.py", line 358, in get
    self._module_cache[path] = self._load_module_source(name, path)
  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/__init__.py", line 343, in _load_module_source
    module = imp.load_source(full_name, path, module_file)
  File "/ansible-plays/juniper-checks/ansible-assertive/callback_plugins/assertive.py", line 10, in <module>
    from ansible.vars.unsafe_proxy import AnsibleUnsafeText
ImportError: cannot import name AnsibleUnsafeText`

looks like AnsibleUnsafeText is now in lib/ansible/utils/unsafe_proxy.py
altering that path then resulted in an error loading lib.utils_proxy

`Traceback (most recent call last):
  File "/usr/local/bin/ansible-playbook", line 106, in <module>
    exit_code = cli.run()
  File "/usr/local/lib/python2.7/dist-packages/ansible/cli/playbook.py", line 130, in run
    results = pbex.run()
  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/playbook_executor.py", line 89, in run
    self._tqm.load_callbacks()
  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_queue_manager.py", line 178, in load_callbacks
    self._stdout_callback = callback_loader.get(self._stdout_callback)
  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/__init__.py", line 358, in get
    self._module_cache[path] = self._load_module_source(name, path)
  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/__init__.py", line 343, in _load_module_source
    module = imp.load_source(full_name, path, module_file)
  File "/ansible-plays/juniper-checks/ansible-assertive/callback_plugins/assertive.py", line 10, in <module>
    from ansible.lib.utils_proxy import AnsibleUnsafeText
ImportError: No module named lib.utils_proxy`

**Comment by larsks** [comment]
What version of Ansible are you using?

**Comment by larsks** [comment]
Ah, I think I misunderstood your report.  You are reporting a problem between `ansible-assertive` and the current HEAD of the Ansible `dev` branch.  I'll take a look.

**Comment by larsks** [comment]
The fix `ansible.vars.unsafe_proxy` -> `ansible.utils.unsafe_proxy` seems simple (and I have committed it to this repository), but the `devel` branch has some significant changes in how Ansible configuration works.  It will need to either (a) figure out how to write something that works cleanly with both environments or (b) rewrite the code to just use environment variables for configuration.

**Comment by larsks** [comment]
Upon closer examination the new config handling code in Ansible is a train wreck and I'm not going to go anywhere near it.
